name: Tag Job
run-name: This run when a new tag is created 🚀
on:
  create:
    tags:
      - '*'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: echo "The new created tag is ${{ env.RELEASE_VERSION }} "
  connName:
    id: read_property
    uses: christian-draeger/read-properties@1.1.1
    with:
      path: './module.properties'
      properties: 'name'
    run: echo ${{ steps.read_property.outputs.name }}
  http:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        id: req
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://httpbin.org/headers'
          method: 'GET'
          customHeaders: '{"Testing": "Gabriel"}'
      - name: Response
        run: |
          echo ${{ steps.req.outputs.response }}